
require 'faker'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#users

User.destroy_all


users = [
    {name: "Adam Altmark", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U014ZJ9KUBA-e011fe7b1973-512"},
    {name: "Alex Ortiz", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149P2DPGA-5bc46d19c029-512"},
    {name: "Andrew Santos", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-UL8B585HP-14e7e4df1c70-512"},
    {name: "Andy Agus", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-UQTV5GEFM-59b31a47e35f-512"},
    {name: "Berel Levy", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149V71ZRR-179071fd3f16-512"},
    {name: "Brandon Gubitosa", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149P2ATLJ-a175739d4005-512"},
    {name: "Corey Lynch", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U011LC0U7GW-f7b87b95c922-512"},
    {name: "Daniel Reyes", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0136GZTQSG-77e66445bb6c-512"},
    {name: "Dolly Desir", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0130BRC3K4-9001c9b22325-512"},
    {name: "Jeffrey Musselman", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-UMC62QVAM-019eb6bf04b1-512"},
    {name: "Leamsi Escribano", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149P2CRNE-50a2d608ab6c-512"},
    {name: "Malcolm Staso", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U014ZJ9F1K2-d9c4863dcd04-512"},
    {name: "Maleeha Bhuiyan", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0148BWV805-946025995b60-512"},
    {name: "Maxwell Croy", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U014DQ3SKMK-8164c7778a8b-512"},
    {name: "Maya Blevins", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149V711B5-b550a063d7f8-512"},
    {name: "Melody Soriano", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149P29UH0-611bbf796682-512"},
    {name: "Muhammad Hassan", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U014ZJ9C4HE-3e3623a4de5d-512"},
    {name: "Paola Dolcemascolo", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-UUNMDGQHG-384b0c170392-512"},
    {name: "Rebecca Rosenberg", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U014ZJ9E3RN-0006b89adbe7-512"},
    {name: "Rudy Guerrero", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U013V17QKQF-b9866186602f-512"},
    {name: "Shadman Ahmed", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149V6VD1R-25fe7ef5f450-512"},
    {name: "Shiro Han", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149P28WBU-de0d070dd1f1-512"},
    {name: "Stephen Galvan", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U014ZJ9GY6L-aca36055b09d-512"},
    {name: "Tashawn Williams", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U7PSME4DA-8b811931b3d9-512"},
    {name: "Travis Prol", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U0149P2ES90-c5e480b910c1-512"},
    {name: "Eric Kim", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U91CXSUN4-3bac0a7f6a08-512"},
    {name: "Greg Dwyer", password: Faker::Internet.password(min_length: 10, max_length: 20, mix_case: true, special_characters: true) ,username: Faker::Superhero.name, email: Faker::Internet.email, user_img_url: "https://ca.slack-edge.com/T02MD9XTF-U8H2RA3C1-643c8ce562ef-512"}
   ]
   
   puts '...creating users'
   users.each do |user|
       User.create(user)
   end

# pets

Pet.destroy_all

pet1 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://i.ytimg.com/vi/MPV2METPeJU/maxresdefault.jpg")
pet2 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://d17fnq9dkz9hgj.cloudfront.net/breed-uploads/2018/09/dog-landing-hero-lg.jpg?bust=1536935129&width=1080")
pet3 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.humanesociety.org/sites/default/files/styles/1240x698/public/2019/02/dog-451643.jpg?h=bf654dbc&itok=MQGvBmuo")
pet4 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/17140825/Swedish-Vallhund-head-portrait-outdoors.jpg")
pet5 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg")
pet6 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322868_1100-1100x628.jpg")
pet7 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/golden-retriever-royalty-free-image-506756303-1560962726.jpg?crop=0.672xw:1.00xh;0.166xw,0&resize=640:*")
pet8 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.guidedogs.org/wp-content/uploads/2019/11/website-donate-mobile.jpg")
pet9 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.nationalgeographic.com/content/dam/animals/thumbs/rights-exempt/mammals/d/domestic-dog_thumb.jpg")
pet10 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2016/05/19091354/Weimaraner-puppy-outdoors-with-bright-blue-eyes.20190813165758508-1.jpg")
pet11 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://i.guim.co.uk/img/media/fe1e34da640c5c56ed16f76ce6f994fa9343d09d/0_174_3408_2046/master/3408.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=67773a9d419786091c958b2ad08eae5e")
pet12 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.aspca.org/sites/default/files/blog_make-dogs-day_101619_main.jpg")
pet13 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.sciencemag.org/sites/default/files/styles/article_main_large/public/pearl_16x9.jpg?itok=jZ8iPy1q")
pet14 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://s.abcnews.com/images/Health/dog-gty-jpo-190608_hpMain_16x9_992.jpg")
pet15 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.cdc.gov/healthypets/images/pets/cute-dog-headshot.jpg")
pet16 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.thesprucepets.com/thmb/mERLXPcXz4U9G702HlsORXJqZrU=/4231x2380/smart/filters:no_upscale()/adorable-white-pomeranian-puppy-spitz-921029690-5c8be25d46e0fb000172effe.jpg")
pet17 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://9b16f79ca967fd0708d1-2713572fef44aa49ec323e813b06d2d9.ssl.cf2.rackcdn.com/1140x_a10-7_cTC/018-5207-1581118435.jpg")
pet18 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.pennmedicine.org/news/-/media/images/pr%20news/news/2018/may/summerdog.ashx?h=263&w=400&la=en")
pet19 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://ca-times.brightspotcdn.com/dims4/default/fd7cb3e/2147483647/strip/true/crop/1024x682+0+0/resize/840x559!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F98%2Ffd%2F93ea3610d890b1a19585b0ed2175%2Fsd-san-diego-puppy-20180711")
pet20 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://westvalleyhumanesociety.org/wp-content/uploads/2019/09/3.jpg")
pet21 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.aaha.org/contentassets/3c00345bcc2d430b9f471734e8417d75/2019-6-6-istock-460588321-osu-mean-dog-blog.jpg")
pet22 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://i.insider.com/5484d9d1eab8ea3017b17e29?width=1136&format=jpeg")
pet23 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://s.hdnux.com/photos/01/11/67/30/19363365/3/920x920.jpg")
pet24 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.guidedogs.org/wp-content/uploads/2018/01/Mobile.jpg")
pet25 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/smartest-dog-breeds-1553287693.jpg?crop=0.673xw:1.00xh;0.167xw,0&resize=640:*")
pet26 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/13142848/Cavalier-King-Charles-Spaniel-standing-in-the-grass.jpg")
pet27 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://scx2.b-cdn.net/gfx/news/hires/2018/2-dog.jpg")
pet28 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://upload.wikimedia.org/wikipedia/commons/0/01/Dhole_%28Asiatic_wild_dog%29_cropped.jpg")
pet29 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.connexionfrance.com/var/connexion/storage/images/_aliases/articleimage/media/images/german-shepherd-dog-by-cheryl-cox/1053199-1-eng-GB/German-Shepherd-dog-by-Cheryl-Cox.jpg")
pet30 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2020/04/931/524/DogLonelyIstock2.jpg?ve=1&tl=1")
pet31 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://thestacker.com/sites/default/files/styles/properly_sized_image/public/2020-03/English%20Lab%20Puppy%20%281%29_0.png")
pet32 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://images.unsplash.com/photo-1566903451935-7e8835ed3e97?ixlib=rb-1.2.1&w=1000&q=80")
pet33 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://thehappypuppysite.com/wp-content/uploads/2018/04/when-can-puppies-go-outside-header.jpg")
pet34 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.readersdigest.ca/wp-content/uploads/2013/03/6-facts-to-know-before-owning-a-puppy.jpg")
pet35 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.gannett-cdn.com/presto/2019/12/18/USAT/5c51582a-64cb-4079-8584-b7bdf9dae701-GettyImages-1130714351.jpg")
pet36 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.rd.com/wp-content/uploads/2020/02/GettyImages-1050600824-1024x683.jpg")
pet37 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://images.unsplash.com/photo-1530667912788-f976e8ee0bd5?ixlib=rb-1.2.1&w=1000&q=80")
pet38 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.rover.com/blog/wp-content/uploads/2019/07/maltese-puppy.jpg")
pet39 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://bullyade.com/wp-content/uploads/2019/07/best-vitamins-for-puppies.jpg")
pet40 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://steemitimages.com/DQmQRdNG9Tagz7dgUarjApuBVSRPDQNJUKpuuhchA4fHHKC/IMG_0637a.jpg")
pet41 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://media11.s-nbcnews.com/j/MSNBC/Components/Video/201906/OLDDOG_THUMBNAIL.focal-760x428.jpg")
pet42 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2009/01/12214509/blind-old-dog-800x600.jpg")
pet43 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/articles/health_tools/dog_picky_eater_slideshow/thinkstock_rf_old_dog.jpg?resize=650px:*")
pet44 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://www.bestprotectiondogs.org/wp-content/uploads/2019/11/66B0D798-76FC-455D-AB7B-E28ACBCA5DC3-1024x682.jpeg")
pet45 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://media4.s-nbcnews.com/i/newscms/2016_52/1184388/rescue-group-old-dog-haven-today-161226-tease-01_00bac92f7fa6330b327ff47cdd4acdf2.jpg")
pet46 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://i.insider.com/5efe3d7faee6a8324a656478?width=1100&format=jpeg&auto=webp")
pet47 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://frontiersinblog.files.wordpress.com/2020/01/frontiers-psychology-stray-dogs-human-cues-behavior.jpg?w=1000")
pet48 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://s3.amazonaws.com/petcentral.com/wp-content/uploads/2020/01/03114844/how_old_is_the_oldest_dog-1-940x503.jpg")
pet49 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/articles/health_tools/dog_picky_eater_slideshow/thinkstock_rf_old_dog.jpg?resize=650px:*")
pet50 = Pet.create(user_id:nil, name: Faker::FunnyName.name, age: rand(1..15), breed: Faker::Creature::Dog.breed, description: Faker::Creature::Dog.meme_phrase, pet_img_url:"https://embarkvet.com/wp-content/uploads/2018/03/embark-old-golden.jpg")


#post 

Post.destroy_all

post1 = Post.create(user_id: User.all.sample.id, post_title: "Cinderella never asked for a prince.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.pinimg.com/originals/87/b1/56/87b156f6e5c01c9b71e22be8b62af300.jpg")
post2 = Post.create(user_id: User.all.sample.id, post_title: "Hey you. Yeah, you. I love you.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.pinimg.com/originals/a4/1b/35/a41b35902edf063b210daf94a57ec764.jpg")
post3 = Post.create(user_id: User.all.sample.id, post_title: "Hey, I just met you, this is crazy.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://cuteanimalsland.files.wordpress.com/2018/05/tumblr_oicwzc04f41rx1zuco1_540.jpg?w=700")
post4 = Post.create(user_id: User.all.sample.id, post_title: "I am happiest when I’m right next to you.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.imgur.com/v6wUNbu_d.webp?maxwidth=728&fidelity=grand")
post5 = Post.create(user_id: User.all.sample.id, post_title: "I don’t have friends, I have a family.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://data.whicdn.com/images/260521219/original.jpg")
post6 = Post.create(user_id: User.all.sample.id, post_title: "I can show you the world.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://previews.123rf.com/images/pressmaster/pressmaster1412/pressmaster141201261/34897099-cheerful-family-of-four-and-their-cute-dog.jpg")
post7 = Post.create(user_id: User.all.sample.id, post_title: "Mom: Why is everything on the floor? Me: Gravity!", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://en.bcdn.biz/Images/2016/6/24/a0da1a7c-bfba-4659-9833-a5c9393746f8.jpg")
post8 = Post.create(user_id: User.all.sample.id, post_title: "The truest form of best friendship is the friendship between a mom and her daughter.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://lh3.googleusercontent.com/proxy/sKs2xCkx74EsXnOxYDyawywwW9PYl4ckWT-pvDc8PXc48XOkb-BHK85gOO83r9iU25RHOi5xssVkPRZfDRum4Bpcjy0PibJTHpAUktWInea9445n")
post9 = Post.create(user_id: User.all.sample.id, post_title: "There’s nothing that can help you understand your beliefs more than trying to explain them to an inquisitive child.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i1.wp.com/www.legacypet.co.za/wp-content/uploads/2015/08/slide03-family-dog.jpg?ssl=1")
post10 = Post.create(user_id: User.all.sample.id, post_title: "Together we make a family.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://energync.org/wp-content/uploads/2017/04/iStock_000020612034_XXXLarge_small.jpg")
post11 = Post.create(user_id: User.all.sample.id, post_title: "As beautiful on the inside as I am on the outside.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i1.wp.com/petfriendlysites.com/wp-content/uploads/2018/01/alaska-couple-finds-floof-pup-in-the-woods-now-hes-a-part-of-their-3-dog-family.jpg")
post12 = Post.create(user_id: User.all.sample.id, post_title: "A stiletto in a room full of flats.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://static.boredpanda.com/blog/wp-content/uploads/2014/01/funny-dogs-in-cars-lara-jo-regan-7.jpg")
post13 = Post.create(user_id: User.all.sample.id, post_title: "I’m just saying you could do better", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.imgur.com/SX9jAF0.jpg")
post14 = Post.create(user_id: User.all.sample.id, post_title: "Make them stop and stare.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2018/03/08144431/golden-retriever-puppies-running-behind-mom.jpg")
post15 = Post.create(user_id: User.all.sample.id, post_title: "On my worst behavior", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://barkpost.com/wp-content/uploads/2015/08/16-Mother-dog-sitting-with-her-puppies.jpg")
post16 = Post.create(user_id: User.all.sample.id, post_title: "Shut up, I think you are gorgeous", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.dhresource.com/0x0/f2/albu/g7/M00/E1/E9/rBVaSlq4inuAIWV2AAbvc40yqeQ274.jpg")
post17 = Post.create(user_id: User.all.sample.id, post_title: "All I need is Coffee and Mascara.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i5.walmartimages.com/asr/3799a39d-a421-44b9-85ec-fb0786f03817_1.8dd27472cac72a07b1a16940116bcf46.jpeg")
post18 = Post.create(user_id: User.all.sample.id, post_title: "Born to express, not to impress.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i1.pickpik.com/photos/188/415/786/animals-cute-dogs-family-preview.jpg")
post19 = Post.create(user_id: User.all.sample.id, post_title: "But first, lipstick", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://besthqwallpapers.com/Uploads/21-8-2018/62483/thumb2-golden-retriever-4k-lawn-mother-and-cub-labradors.jpg")
post20 = Post.create(user_id: User.all.sample.id, post_title: "Confidence level: Kanye West.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.dhresource.com/600x600/f2/albu/g8/M00/81/B9/rBVaV1wsajSATiOrAAM_j7Kbd-k618.jpg")
post21 = Post.create(user_id: User.all.sample.id, post_title: "Curls run the world.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/07160854/Lakeland-Terrier-puppies-sitting-outdoors.jpg")
post22 = Post.create(user_id: User.all.sample.id, post_title: "Do you like this dress?", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/at%2Farchive%2F562c5604a26baa7131257705e41b99973b2c8d89")
post23 = Post.create(user_id: User.all.sample.id, post_title: "Give a girl the right Hairstyle and she will Conquer the world.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://reason.com/wp-content/uploads/2018/08/15342840158842-1-856x630.jpg")
post24 = Post.create(user_id: User.all.sample.id, post_title: "How on earth do you make a good selfie?! Why do I always turn out like a goblin?", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://imgix.bustle.com/uploads/getty/2018/8/18/7087d3af-4c79-48e2-bc5d-6ca90b0602a6-getty-117587726.jpg")
post25 = Post.create(user_id: User.all.sample.id, post_title: "I did NOT wake up like this.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://images.squarespace-cdn.com/content/v1/5a3adeb11f318d9dd2dfadaa/1527611880550-6DUOWKQ67ULOTK1ODMLQ/ke17ZwdGBToddI8pDm48kFVfgRqeiJbezCllpJQtY_0UqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKciN1LM1HpqVwNixpz1hCKq8qoxvRXzjNTQ09MieJKwtnXQQXYw_DH5ZQqvplaE488/puppies.jpg")
post26 = Post.create(user_id: User.all.sample.id, post_title: "I don’t sweat—I sparkle.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.insider.com/5ecd5a395af6cc28c6787263?width=1100&format=jpeg&auto=webp")
post27 = Post.create(user_id: User.all.sample.id, post_title: "I have enough jewelry – Said no one ever!", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://resc-files-prod.s3.us-west-1.amazonaws.com/s3fs-public/styles/large/public/2018-12/Puppy-Development-Atlanta-Puppies-9344sak_1.jpg?itok=91SPggCy")
post28 = Post.create(user_id: User.all.sample.id, post_title: "I have never seen elegance go out of style.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F20%2F2020%2F06%2F22%2Ffrench-bulldog-puppies.jpg")
post29 = Post.create(user_id: User.all.sample.id, post_title: "I know I am Awesome, so I don’t care about your opinion..!!", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://images-na.ssl-images-amazon.com/images/I/51pn4A4VnML._AC_.jpg")
post30 = Post.create(user_id: User.all.sample.id, post_title: "I’m a queen crowned in my curls", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://e3.365dm.com/19/12/1600x900/skynews-puppies-dogs_4870599.jpg?20191219074652")
post31 = Post.create(user_id: User.all.sample.id, post_title: "I’m an odd combination of “REALLY SWEET” and “DON’T MESS WITH ME”!!!", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://puplifetoday.com/wp-content/uploads/2018/07/dog-food-for-puppies.jpg")
post32 = Post.create(user_id: User.all.sample.id, post_title: "I’m an original and that’s perfection in itself", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.pets4homes.co.uk/images/articles/3145/large/how-when-to-switch-puppies-to-adult-food-55ca0fb9633dd.jpg")
post33 = Post.create(user_id: User.all.sample.id, post_title: "If you’re going to be two-faced, at least make one of them pretty.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.rover.com/blog/wp-content/uploads/2017/05/puppies-together-960x540.jpg")
post34 = Post.create(user_id: User.all.sample.id, post_title: "Isn’t it beautiful outside?", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://husse-eu.global.ssl.fastly.net/media/klaro_news/1503408291628781766.jpg")
post35 = Post.create(user_id: User.all.sample.id, post_title: "It doesn’t matter what anyone else thinks of me because I know who I am, and I am damn proud of it.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://thehappypuppysite.com/wp-content/uploads/2018/03/puppy-training-stages-header.jpg")
post36 = Post.create(user_id: User.all.sample.id, post_title: "It’s good to live expensively, you know it.”", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.guim.co.uk/img/media/fccf2d648bd42dae41b65cad55925181506ec5e7/0_117_6016_3611/master/6016.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=1a6ae016322e5bf310e4351808be2235")
post37 = Post.create(user_id: User.all.sample.id, post_title: "It’s okay to be a glow stick; sometimes we need to break before we shine.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.pocklingtonpost.co.uk/webimg/QVNIMTE0Nzg2MTY0.jpg")
post38 = Post.create(user_id: User.all.sample.id, post_title: "Just like my eyeliner, I always wing it", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.ctvnews.ca/polopoly_fs/1.4937754.1589389981!/httpImage/image.jpg_gen/derivatives/landscape_620/image.jpg")
post39 = Post.create(user_id: User.all.sample.id, post_title: "Keep smiling because life is a beautiful thing and there’s so much to smile about.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.madpaws.com.au/wp-content/uploads/2018/11/golden-retriever-puppy-2706672_1920.jpg")
post40 = Post.create(user_id: User.all.sample.id, post_title: "Leave a little sparkle everywhere you go", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://cdn.theatlantic.com/thumbor/-QzjtbaxGucPwSD86ZxDv-y7MuI=/900x601/media/img/photo/2019/03/national-puppy-day-photos/p01_556211362/original.jpg")
post41 = Post.create(user_id: User.all.sample.id, post_title: "Life is too short for boring hair.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://stmedia.stimg.co/ows_154732781991511.jpg?fit=crop&crop=faces")
post42 = Post.create(user_id: User.all.sample.id, post_title: "Life isn’t perfect but your outfit can be.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://storage.googleapis.com/afs-prod/media/media:73c4408577d1483f8eeedab4a8ce260c/800.jpeg")
post43 = Post.create(user_id: User.all.sample.id, post_title: "All I want to do is taco’ about you.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.aspca.org/sites/default/files/blog_florida-pet-store-puppies_021418_main.jpg")
post44 = Post.create(user_id: User.all.sample.id, post_title: "I donut know what I would do without you.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://imgix.bustle.com/uploads/image/2019/10/10/14a6b1e6-c5e8-49f0-98d8-0dd8a32a03c2-screen-shot-2019-10-10-at-35357-pm.png")
post45 = Post.create(user_id: User.all.sample.id, post_title: "I love you a latte.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2018/3/22/0/shutterstock_national-puppy-day-301891139.jpg.rend.hgtvcom.966.725.suffix/1521744692471.jpeg")
post46 = Post.create(user_id: User.all.sample.id, post_title: "License To Chill", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://imageresizer.static9.net.au/7xAEJQhdBHs3yz6VCGs_U2ZcHxQ=/400x0/https%3A%2F%2Fprod.static9.net.au%2F_%2Fmedia%2F2018%2F10%2F29%2F16%2F28%2F1_puppyhalloween.jpg")
post47 = Post.create(user_id: User.all.sample.id, post_title: "Salty BUT sweet.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.pinimg.com/736x/1d/16/d1/1d16d183b477300362527e8f8c90beb1.jpg")
post48 = Post.create(user_id: User.all.sample.id, post_title: "A coffee can’t solve everything but it can solve a lot", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.pinimg.com/originals/5b/51/47/5b5147dd7859448ba52271b0cdc4e8fb.jpg")
post49 = Post.create(user_id: User.all.sample.id, post_title: "Be a beautiful cupcake in a world full of muffins.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2014/8/7/1/original_Camille-Smith-fairy-dog-costume-Phoebe-beauty.jpg.rend.hgtvcom.966.725.suffix/1409064045201.jpeg")
post50 = Post.create(user_id: User.all.sample.id, post_title: "Be a Fruit Loop in a world full of Cheerios", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.pinimg.com/originals/0f/8b/d8/0f8bd81284c177977497fe8748af1e9a.jpg")
post51 = Post.create(user_id: User.all.sample.id, post_title: "Chocolate doesn’t ask silly questions, chocolate understands – just like best friends!", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://media1.popsugar-assets.com/files/thumbor/muYE0ZrB3hmmLbFozck6xDcftzA/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2016/07/30/141/n/1922441/5d474b2e_edit_img_image_38287495_1446228000_11357536_593801900763018_2096355407_n/i/DIY-Dog-Costumes.jpg")
post52 = Post.create(user_id: User.all.sample.id, post_title: "Coffee and confidence and camera.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://i.pinimg.com/originals/65/2d/b4/652db4d745f24afecdf5b0d3d666fed0.jpg")
post53 = Post.create(user_id: User.all.sample.id, post_title: "Eat, drink, and be cozy.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://vittlesvault.com/wp-content/uploads/2017/10/DIY-wonder-bread-loaf-Dog-Halloween-Costume.jpg")
post54 = Post.create(user_id: User.all.sample.id, post_title: "Friends buy you food. Best friends eat your food.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://cdn.shopify.com/s/files/1/0073/5382/files/rocket_dog_large.jpg?v=1538420119")
post55 = Post.create(user_id: User.all.sample.id, post_title: "Hello Starbucks? Can i have a mocha good luck please?", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://media1.popsugar-assets.com/files/thumbor/C04Z8ssCUV7WLn_lwmOTLD2haz0/358x0:3543x3185/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2019/08/07/730/n/44701584/2a00446a5d4afd18bde650.59840750_/i/Pictures-Dogs-Making-Funny-Faces.jpg")
post56 = Post.create(user_id: User.all.sample.id, post_title: "Give me the chocolate and nobody gets hurt", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://2.bp.blogspot.com/-kLEl6xe3r_k/Uw4WU7yb7_I/AAAAAAAADh8/SKY56uJHWns/s1600/10.jpg")
post57 = Post.create(user_id: User.all.sample.id, post_title: "How to do you reward yourself after a long day?", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://66.media.tumblr.com/ba9cf4297ac8c27cde6fd85c1fed4b21/tumblr_pcq1bsaABB1v46tua_640.jpg")
post58 = Post.create(user_id: User.all.sample.id, post_title: "Hard times will always reveal true friends.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://www.dumpaday.com/wp-content/uploads/2013/03/funny-dog-faces-21.jpg")
post59 = Post.create(user_id: User.all.sample.id, post_title: "Friendship is…being equally annoying.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://cdn.akc.org/content/article-body-image/funny-springer_spaniel.jpg")
post60 = Post.create(user_id: User.all.sample.id, post_title: "Friends who slay together, stay together.", description: Faker::Lorem.paragraph(sentence_count: 4), post_img_url: "https://media1.popsugar-assets.com/files/thumbor/4m-Wm2CZRZZmFlfg1rfIGvSGOiI/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2019/08/06/770/n/44701584/62ab9d91c63acb11_GettyImages-85376149/i/Pictures-Dogs-Making-Funny-Faces.jpg")
